apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mp-api
  template:
    metadata:
      labels:
        app: mp-api
    spec:
      containers:
      - name: mp-api
        image: mp-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000